# Scan for available migrations when dependency files change in a PR.
# Posts a comment with scan results — does not create a separate PR.

name: Dependency Scan
on:
  pull_request:
    paths:
      - 'requirements*.txt'
      - 'pyproject.toml'
      - 'setup.cfg'
      - 'Pipfile'

permissions:
  contents: read
  pull-requests: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Ragab-Technologies/codeshift@v1
        id: codeshift
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          create-pr: 'false'
          run-tests: 'false'
          tier1-only: 'true'

      - name: Comment on PR
        if: steps.codeshift.outputs.migrations-count != '0'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Codeshift Scan Results\n\n` +
                `Found **${{ steps.codeshift.outputs.migrations-count }}** available migration(s) ` +
                `affecting **${{ steps.codeshift.outputs.files-changed }}** file(s).\n\n` +
                `Risk level: **${{ steps.codeshift.outputs.risk-level }}**\n\n` +
                `Run \`codeshift upgrade-all --tier1-only\` locally or trigger the migration workflow to apply.`
            })
